[package]
name = "genetic"
version = "0.1.0"
edition = "2021"

[lib]
name = "genetic"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
serde = "1.0.175"
serde_json = "1.0.85"
